name: flutter_wiggles
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sailec
      fonts:
        - asset: assets/fonts/sailec_bold.otf
          weight: 700
        - asset: assets/fonts/sailec_medium.otf
          weight: 500
        - asset: assets/fonts/sailec_regular.otf
          weight: 400
